name: Deploy to stag
on:
  push:
    branches: [stag]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Deploy app to stag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - uses: canastro/copy-file-action@master
        with:
          source: 'deployment/environments/serverless-staging.yml'
          target: 'serverless.yml'

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install npm dependencies
        run: npm install

      - name: Deploy app
        run: npx serverless@2.72.2

      - name: Sync '.serverless' state
        run: aws s3 sync .serverless s3://website-serverless-state-bucket/website/staging/.serverless --delete
